version: '3.8'

services:
  crm:
    build:
      context: ../..
      dockerfile: src/crm/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=/app/data/crm.db
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped 